### ISSUE TITLE
fastnode causing excessive disk thrashing 

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/iavl#606]
When nodes on mainnets upgraded to iavl with fast node support we saw a large amount of them have increased Read and Write throughput. Higher than the expected amount in some cases. We should diagnose this and see if it's possible to improve it.

**Comment by RusAkh** [comment]
I would like to investigate that

**Comment by giskook** [comment]
Hi, We met this situation too. any thing I can help?

**Comment by RusAkh** [comment]
![iavl_dif_full_720](https://user-images.githubusercontent.com/46343690/203022804-0b30eef4-12ac-448a-94ee-8501021376ce.png)

This is the disk performance from 2 completely identical nodes, but on one `fastnode` is enabled and on the other - not. You can see that usage is the same, which is a little odd. As @tac0turtle said, it is expected to have a higher amount of io usage due to storing additional keys on disk.

**Comment by RusAkh** [comment]
![](https://files.slack.com/files-pri/T029MTBCX40-F04AZUFE8NB/iavl_diff.png)

This comparison is less polluted with info

**Comment by tac0turtle** [comment]
closing this for now as fastnodes will be removed in v2
